apiVersion: v1
kind: Pod
metadata:
  name: emptydir-vol
spec:
  containers:
    - name: busybox
      image: docker.io/library/busybox:stable
      imagePullPolicy: Never
      command:
        [
          "sh",
          "-c",
          "echo 'Writing to the empty dir...' > /data/data.txt; cat /data/data.txt",
        ]
      volumeMounts:
        - name: emptydir-volume
          mountPath: /data
  volumes:
    - name: emptydir-volume
      emptyDir: {}
