apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-test
spec:
  containers:
    - name: busybox
      image: docker.io/library/busybox:stable
      imagePullPolicy: Never
      command: ["sh", "-c", "cat /data/data.txt"]
      volumeMounts:
        - name: hostpath-volume
          mountPath: /data
  volumes:
    - name: hostpath-volume
      hostPath:
        path: /etc/hostPath # This is a location directly on the node
        type: Directory # Multiple types are available -> go through them
