apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-worker-pod-template
  namespace: airflow
data:
  worker-pod-template.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        app: airflow
        component: worker
    spec:
      containers:
        - name: base
          image: apache/airflow:2.7.2-python3.10
          command: ["airflow", "worker"]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://postgres:mysecretpassword@postgres:5432/airflow
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
          volumeMounts:
            - name: airflow-logs
              mountPath: /opt/airflow/logs
      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-pvc
      restartPolicy: Never
